In [3]:
import numpy as np

## DataTypes & Attributes

In [4]:
# Numpy's main datatype is n-array
a1 = np.array([1,2,3])
a1

array([1, 2, 3])

In [5]:
type(a1)

numpy.ndarray

In [6]:
a2 = np.array([[1,2,3,],[4,5,6.5]])

a3 = np.array([[[1,2,3],
                [4,5,6],
                [7,8,9]],
               [[10,11,12],
                [13,14,15],
                [16,17,18]]])

In [7]:
a2

array([[1. , 2. , 3. ],
       [4. , 5. , 6.5]])

In [8]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [9]:
a1.shape

(3,)

In [10]:
a2.shape

(2, 3)

In [11]:
a3.shape

(2, 3, 3)

In [12]:
# dimention
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

In [13]:
a1.dtype, a2.dtype, a3.dtype

(dtype('int32'), dtype('float64'), dtype('int32'))

In [14]:
a1.size, a2.size, a3.size

(3, 6, 18)

In [15]:
type(a1), type(a2), type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [16]:
# Create a DataFrame from a Numpy array
import pandas as pd

df = pd.DataFrame(a2)
df

0    1    2
0  1.0  2.0  3.0
1  4.0  5.0  6.5

## 2. Creating arrays

In [17]:
sample_array = np.array([1,2,3])
sample_array

array([1, 2, 3])

In [18]:
sample_array.dtype

dtype('int32')

In [19]:
ones = np.ones((2,3))

In [20]:
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [21]:
zeros = np.zeros((2,3))

In [22]:
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [23]:
range_array = np.arange(0,10,2)
range_array

array([0, 2, 4, 6, 8])

In [24]:
random_array = np.random.randint(0,10,size=(3,5))
random_array

array([[5, 2, 0, 2, 3],
       [5, 3, 1, 1, 9],
       [9, 6, 3, 8, 7]])

In [25]:
random_array_2 = np.random.random((5,3))
random_array_2

array([[0.94995121, 0.53524849, 0.81094195],
       [0.25235073, 0.68135536, 0.43260699],
       [0.32545993, 0.46651758, 0.4830926 ],
       [0.72075721, 0.5205789 , 0.87079013],
       [0.38658954, 0.84781988, 0.29835994]])

In [26]:
random_array_3 = np.random.rand(5,3)
random_array_3

array([[0.3423397 , 0.53136041, 0.42776319],
       [0.17594827, 0.55607269, 0.86600445],
       [0.60103094, 0.23971929, 0.57590267],
       [0.26030379, 0.37579754, 0.05379151],
       [0.61761434, 0.59102322, 0.28499537]])

In [27]:
# Pseudo-random numbers
np.random.seed(0)
random_array_4 = np.random.randint(10, size=(5,3))
random_array_4

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]])

## 3. Viewing arrays and matrics

In [29]:
np.unique(random_array_4)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [30]:
a1

array([1, 2, 3])

In [31]:
a2

array([[1. , 2. , 3. ],
       [4. , 5. , 6.5]])

In [32]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

## 4. Manipulating & comparing arrays

### Arithmetic

In [33]:
a1

array([1, 2, 3])

In [35]:
ones = np.ones(3)

In [36]:
a1 + ones

array([2., 3., 4.])

In [37]:
a2 * a3

ValueError: operands could not be broadcast together with shapes (2,3) (2,3,3) 

In [38]:
# How can you reshape a2 to be compatible with a3?
# reshape numpy array



### Aggregation

Aggregation = performing the same operation on a number of things

In [39]:
listy_list = [1,2,3]
type(listy_list)

list

In [40]:
sum(listy_list)

6

## Dot product exmaple (nut butter sales)

In [42]:
np.random.seed(0)
sales_amounts = np.random.randint(20, size=(5,3))
sales_amounts

array([[12, 15,  0],
       [ 3,  3,  7],
       [ 9, 19, 18],
       [ 4,  6, 12],
       [ 1,  6,  7]])

In [43]:
# Create weekly_sales DataFrame
weekly_sales = pd.DataFrame(sales_amounts,
                            index=["Mon", "Tues", "Wed", "Thurs", "Fri"],
                            columns=["Almond butter", "Peanut butter", "Cashew butter"])
weekly_sales

Almond butter  Peanut butter  Cashew butter
Mon               12             15              0
Tues               3              3              7
Wed                9             19             18
Thurs              4              6             12
Fri                1              6              7

In [48]:
prices = np.array([10,8,12])
prices

array([10,  8, 12])

In [49]:
prices.shape

(3,)

In [47]:
butter_prices = pd.DataFrame(prices.reshape(1,3),
                             index=["Price"],
                             columns=["Almond butter", "Peanut butter", "Cashew butter"])
butter_prices

Almond butter  Peanut butter  Cashew butter
Price             10              8             12

In [51]:
sales_amounts

array([[12, 15,  0],
       [ 3,  3,  7],
       [ 9, 19, 18],
       [ 4,  6, 12],
       [ 1,  6,  7]])

In [55]:
sales_amounts.shape

(5, 3)

In [56]:
total_sales = prices.dot(sales_amounts.T)

In [57]:
total_sales

array([240, 138, 458, 232, 142])

In [58]:
butter_prices, weekly_sales

(       Almond butter  Peanut butter  Cashew butter
 Price             10              8             12,
        Almond butter  Peanut butter  Cashew butter
 Mon               12             15              0
 Tues               3              3              7
 Wed                9             19             18
 Thurs              4              6             12
 Fri                1              6              7)

## 6. Practical Example - NumPy in Action!!!

<img src="images/panda.png"/>

In [63]:
# Turn an image into a NumPy array
from matplotlib.image import imread

panda = imread("images/panda.png")
print(type(panda))

<class 'numpy.ndarray'>


In [64]:
panda

array([[[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       [[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       [[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       ...,

       [[0.13333334, 0.07450981, 0.05490196],
        [0.12156863, 0.0627451 , 0.04313726],
        [0.10980392, 0

In [65]:
panda.size, panda.shape, panda.ndim

(24465000, (2330, 3500, 3), 3)

<img src="images/car-photo.png"/>